CREATE OR REPLACE PACKAGE TUMT_MAIN AS
TYPE C_PENDING_PAYMENTS_CURSOR IS REF CURSOR;
TYPE C_LAST5_DETAILS_CURSOR IS REF CURSOR;

PROCEDURE sp_PaymentArrived
(P_ACCPAC_REF_NO IN VARCHAR2,P_ACCPAC_USERNAME IN VARCHAR2,P_ACCPAC_DEALER_ID IN VARCHAR2,
 P_ACCPAC_ORDER_ID IN VARCHAR2,P_ACCPAC_TIMESTAMP IN timestamp,P_AMOUNT IN NUMBER,
 P_TUM_TRANSACTION_ID OUT  NUMBER,P_TUM_DB_RESULT OUT  NUMBER);

PROCEDURE sp_BalanceCheck
(P_USERNAME IN VARCHAR2,P_EDGE_DEALER_ID IN VARCHAR2,P_EDGE_TRANSACTION_ID IN VARCHAR2,
 P_EDGE_TIMESTAMP IN DATE,P_TUM_BALANCE OUT NUMBER,P_TUM_TIMESTAMP OUT  DATE,
 P_TUM_TRANSACTION_ID OUT  NUMBER,P_TUM_DB_RESULT OUT  NUMBER,P_PENDING_COUNT OUT NUMBER,
 P_PENDING_REQUESTS OUT C_PENDING_PAYMENTS_CURSOR);

PROCEDURE sp_RechargeSubscriber
(P_ID  OUT NUMBER,P_TRANS_TIME IN DATE,P_TRANS_AMOUNT IN NUMBER ,
 P_SUBSCRIBER_MSISDN IN NUMBER ,P_USERNAME IN VARCHAR2,
 P_EDGE_DEALER_ID IN VARCHAR2,P_EDGE_SUBDEALER_ID IN VARCHAR2 ,
 P_EDGE_TRANSACTION_ID IN NUMBER,P_EDGE_TIMESTAMP IN DATE,P_BEFORE_BALANCE OUT NUMBER,
 P_AFTER_BALANCE OUT NUMBER,P_RESULT_CODE OUT NUMBER,P_ALERT OUT NUMBER);

PROCEDURE sp_RechargeIntermediateTranLog
(P_ID IN NUMBER ,P_EDGE_DEALER_ID IN VARCHAR2,P_EDGE_TRANSACTION_ID IN NUMBER,
 P_EDGE_TIMESTAMP IN DATE,P_TUM_TIMESTAMP IN DATE,P_DB_RESULTCODE IN NUMBER,
 P_DB_RESULTSTRING IN VARCHAR2,P_RETURNCODE OUT NUMBER);

PROCEDURE sp_Recon (P_RECON_DATE in DATE);

PROCEDURE sp_RechargeFinalTranLog
(P_ID IN NUMBER,P_EDGE_TRANSACTION_ID IN NUMBER,P_TUM_TIMESTAMP IN DATE,
P_EDGE_TIMESTAMP IN DATE,P_EDGE_DEALER_ID IN VARCHAR2,P_TUM_DEALER_ID IN VARCHAR2,
P_EDGE_SUBDEALER_ID IN VARCHAR2,P_USERNAME IN VARCHAR2,P_SUBS_MSISDN IN VARCHAR2,
P_TRANS_AMOUNT IN NUMBER,P_BEFORE_BALANCE IN NUMBER,P_AFTER_BALANCE IN NUMBER,
P_DB_RESULTCODE IN NUMBER,P_ACCOUNT_ID IN NUMBER,P_ERROR_DETAIL IN VARCHAR2,
P_STATUS IN NUMBER,P_ALERT_CODE IN NUMBER,P_FINAL_RETURN_CODE OUT NUMBER);

PROCEDURE sp_FinalCSResult
(P_ID IN NUMBER, P_CS_RESULT IN NUMBER, P_CS_TIMESTAMP IN DATE,
P_BEFORE_BALANCE IN NUMBER,P_AFTER_BALANCE IN NUMBER);

PROCEDURE sp_Errors
(P_DATEOF IN DATE,P_SP IN VARCHAR2,P_PARAMETER_SET IN VARCHAR2,P_ERROR_STRING IN VARCHAR2);

PROCEDURE sp_PaymentRegister
(P_USERNAME IN VARCHAR2,P_EDGE_TRANSACTION_ID IN NUMBER,P_TUM_PAYMENT_ID IN NUMBER,
P_EDGE_DEALER_ID IN VARCHAR2,P_EDGE_TIMESTAMP IN DATE,P_ERP_REFERENCE IN VARCHAR2, P_ERP_ORDER_ID IN VARCHAR2,
P_ERP_AMOUNT IN NUMBER, P_TUM_TRANSACTION_ID OUT NUMBER,P_DB_RESULTCODE OUT NUMBER,
P_BALANCE_BEFORE OUT NUMBER,P_BALANCE_AFTER OUT NUMBER);

PROCEDURE sp_cSPassNotFoundLog
(P_RECON_ID IN NUMBER,P_RECON_DATE IN DATE,P_RECON_SCOPE  IN DATE,
P_ORIGINTRANSACTIONID IN NUMBER,P_TRANSACTION_AMOUNT IN NUMBER,P_RECON_STATUS IN NUMBER,
P_TRANSACTION_STATUS IN NUMBER,P_ERROR_DETAIL IN VARCHAR2);

FUNCTION sp_GetDealerType (P_DEALER_ID IN NUMBER) RETURN VARCHAR2;

PROCEDURE sp_PaymentRegisterShop
(P_USERNAME IN VARCHAR2,P_ACCPAC_DEALER_ID IN VARCHAR2,P_ACCPAC_TIMESTAMP IN DATE,
P_ERP_REFERENCE IN VARCHAR2, P_ERP_ORDER_ID IN VARCHAR2,P_ERP_AMOUNT IN NUMBER,
P_ACCPAC_USER IN VARCHAR2,
P_TUM_TRANSACTION_ID OUT NUMBER,P_DB_RESULTCODE OUT NUMBER,P_BALANCE_BEFORE OUT NUMBER,
P_BALANCE_AFTER OUT NUMBER);

PROCEDURE sp_GetLast5Today(P_USERNAME IN VARCHAR2,P_LAST5_CURSOR OUT C_LAST5_DETAILS_CURSOR,P_DBRESULTCODE OUT NUMBER);
PROCEDURE sp_ChangePassword(P_USERNAME IN VARCHAR2,P_REQ_TRANSACTION_ID IN NUMBER,P_REQ_TIMESTAMP IN DATE,
P_DBRESULTCODE OUT NUMBER,P_TUM_TRANSACTION_ID OUT NUMBER);

PROCEDURE sp_ChangePassword1(PUSERNAME IN VARCHAR2,PREQTRANSACTIONID IN NUMBER,PDBRESULTCODE OUT NUMBER,PTUMTRANSACTIONID OUT NUMBER);

END TUMT_MAIN;
/
